[build]
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/index.html#admin"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[template.environment]
  NETLIFY_IDENTITY_ENABLED = "true"

# Enable Git Gateway for content saving
[[plugins]]
  package = "netlify-plugin-git-gateway"
